version: '3'

services:
  lqdemo-local-database:
    image: public.ecr.aws/docker/library/mysql:8
    platform: linux/x86_64
    hostname: rate-all-things-local-database
    container_name: rate-all-things-local-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    ports:
      - "3306:3306"
#    volumes:
#      - ./local_schema_initialisation.sql:/docker-entrypoint-initdb.d/local_schema_initialisation.sql

  redis:
    image: public.ecr.aws/docker/library/redis:6.2-alpine
    hostname: rate-all-things-local-redis
    container_name: rate-all-things-local-redis
    restart: always
    ports:
      - "6379:6379"