# Profile "LOCAL"
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: local
  main:
    banner-mode: console
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 300
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 2048
          plan_parameter_metadata_max_size: 128
  datasource:
    url: jdbc:mysql://localhost-need-to-setting
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  data:
    redis:
      host: localhost
      port: 6379
